#define zero $0
#define AT   $1
#define v0   $2
#define v1   $3
#define a0   $4
#define a1   $5
#define a2   $6
#define a3   $7
#define s0   $16
#define s1   $17
#define s2   $18
#define s3   $19
#define s4   $20
#define s5   $21
#define s6   $22
#define s7   $23
#define t8   $24
#define t9   $25
#define jp   $25
#define k0   $26
#define k1   $27
#define gp   $28
#define sp   $29
#define fp   $30
#define s8   $30
#define ra   $31
.global main
.text
main:
beq s3, s4, label_rhmsacvjgb
move s4, s5
label_rhmsacvjgb:
sll s4, s3, 6
beqz s5, label_pvvtecjlyb
move s3, s4
label_pvvtecjlyb:
sra s3, s4, 9
xori s3, s5, 642
nor s1, s2
and s4, s5
srl s2, s4, 14
andi s2, s3, 2728
nor s4, s6
sltu s2, s1, s3
mult s6, s1
mflo s4
mfhi s1
sltu s1, s3, s2
beqz s4, label_ewplgbepmf
move s5, s2
label_ewplgbepmf:
sra s6, s2, 3
srl s6, s1, 6
bne s2, s1, label_wpdbcphkav
move s1, s6
label_wpdbcphkav:
addu s2, s3
mult s1, s6
mflo s1
mfhi s3
bne s6, 2526, label_eykkyuibne
move s5, s4
label_eykkyuibne:
and s6, s3
mult s1, s3
mflo s1
mfhi s5
